spring:
    application:
        name: blant-monitor
    boot:
        admin:
          routes:
            endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
          turbine:
            clusters: jscloud
            location: turbine
server:
    port: 8764 #启动端口

security:
    user:
        name: monitor
        password: monitor
        role: USER

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://admincenter:admincenter@localhost:8761/eureka/
